spring:
  application:
    name: orderworker
  data:
    mongodb:
      uri: mongodb://localhost:27017/pedidosdb

    redis:
      host: localhost 
      port: 6379    

  kafka:
    bootstrap-servers: localhost:9092 
    consumer:
      group-id: order-worker-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest

external:
  api:
    base-url: http://localhost:8083
    
retry:
  max-attempts: 5

    