spring:
  application:
    name: orderworker
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/pedidosdb}

    redis:
      host: ${SPRING_REDIS_HOST:localhost} 
      port: ${SPRING_REDIS_PORT:6379}


  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:http://localhost:9092}
    consumer:
      group-id: order-worker-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: ${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET:latest}
server:
  port: 8081
  
external:
  api:
    base-url: ${SPRING_EXTERNAL_API_BASE_URL:http://localhost:8083}
    
retry:
  max-attempts: ${SPRING_MAX_ATTEMPTS:5}

    